apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-mysql-deployment
  namespace: default
  labels:
    app: users-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-mysql
  template:
    metadata:
      labels:
        app: users-mysql
    spec:
      containers:
      - name: users-mysql
        image: darsh50/notes-app:users-mysql
        command: ["java"]
        args: ["-jar","/users-mysql.jar","8086"]
        ports:
        - containerPort: 8086
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql/test?useSSL=false
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USER
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
